### ISSUE TITLE
Child Processes Terminating During Upload

### ISSUE THREAD

**Issue by juliamullen** [biothings/biothings.api#101]
Multiple plugins have shown me similar errors related to process pool issues, failing to finish the uploading step.

<img width="662" alt="Screen Shot 2020-11-24 at 2 10 52 PM" src="https://user-images.githubusercontent.com/4401579/100648755-3ce64680-32f6-11eb-9ea2-7ff0eb6fc2e0.png">
<img width="769" alt="Screen Shot 2020-11-24 at 2 11 07 PM" src="https://user-images.githubusercontent.com/4401579/100648756-3e177380-32f6-11eb-9c2f-31a612ff68cf.png">

After one of the plugins fails with this error, no other plugin's uploader can run without running into this error. Restarting the hub fixes the issue temporarily.

**Comment by juliamullen** [comment]
Ultimately this was due to one plugin in particular running into an error. I've annotated the error below for future reference, but it's surprising to me that the plugin could error in such a way to mess up the process pool, and that this specific message was the result (instead of the error that was raised). Still, going to close this ticket as there's no work to be done on the Biothings side to fix this issue in particular.

The error itself was an HTTPError similar to what is described in this [SO question](https://stackoverflow.com/questions/62278538/pd-read-csv-produces-httperror-http-error-403-forbidden). pandas.read_csv() attempts to open a link and gets a 403 Forbidden because of an empty user-agent (the resource in question evidently wanted to restrict access from bots grabbing the link). Running the parser locally returns this, more obvious error w/ traceback:
```
  File "parser.py", line 642, in getWHOTrials
    raw = pd.read_csv(WHO_URL, dtype={"Date registration3": str})
[...]
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

Still not sure why this error in particular fails to render. Upon inspection of the logs, this HTTPError is explicitly printed in `covid_who_clinical_trials.clinicaltrialswho_batch_1_20201129.log`. Unfortunately, `upload_covid_who_clinical_trials.clinicaltrialswho_20201129.log` where I was looking for information, only had the concurrent.futures.process.BrokenProcessPool error with the following traceback:
```

17:21:21 [24426:MainThread] - upload_covid_who_clinical_trials.clinicaltrialswho - ERROR -- failed [steps=data,post,master,clean]: A process in the process pool was terminated abruptly while the future was running or pending.
Traceback (most recent call last):
  File "/opt/home/outbreak/biothings.api/biothings/hub/dataload/uploader.py", line 487, in load
    **kwargs)
  File "/opt/home/outbreak/biothings.api/biothings/hub/dataload/uploader.py", line 362, in update_data
    yield from job
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/opt/home/outbreak/biothings.api/biothings/hub/dataload/uploader.py", line 356, in uploaded
    if type(f.result()) != int:
  File "/opt/home/outbreak/biothings.api/biothings/utils/manager.py", line 691, in run
    res = yield from res
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/opt/home/outbreak/biothings.api/biothings/utils/manager.py", line 685, in ran 
    r = f.result()
```

**Comment by zcqian** [comment]
Pull request #136 should fix this. Will close this issue when PR #136 is merged
