### ISSUE TITLE
mygene.info sources tab fails to load

### ISSUE THREAD

**Issue by juliamullen** [biothings/biothings.api#102]
Console renders the error
TypeError: src.download.dumper.bases is undefined

in the function
displayable 

on the line
DataSourceGrid.vue:113

**Comment by newgene** [comment]
@marcodarko I believe you already fixed it, please tag your commit and close this issue.

**Comment by marcodarko** [comment]
Check if array exists before accessing it https://github.com/biothings/biothings.api/commit/9936e9c3f20d7916458c16ce53246a062a854828
