### ISSUE TITLE
Support OpenAPI metadata generation for BioThings API instance 

### ISSUE THREAD

**Issue by newgene** [biothings/biothings.api#109]
This can be done in two stages:

1. Support creating generic OpenAPI metadata for all API endpoints enabled in a BioThings API instance

2. Support adding OpenAPI extensions (e.g. `x-bte`, `x-translator` extensions supported in SmartAPI.

This issue depends on https://github.com/biothings/biothings.api/issues/105

**Comment by zcqian** [comment]
Partially implemented in PR #103
