### ISSUE TITLE
FTPDumper: set optimal blocksize for known FTP host

### ISSUE THREAD

**Issue by newgene** [biothings/biothings.api#117]
Per: https://ftp.ncbi.nlm.nih.gov/README.ftp, the optimal blocksize for ncbi FTP server is 32MB. The default Python ftplib blocksize is 8192.

Todo for `FTPDumper`:
* allow to set different `blocksize` at dumper class
* keep a set of optimal blocksize for known FTP servers (e.g. ncbi ftp)

Example Dumper: `DBSNPDumper` from MyVariant.info

**Comment by zcqian** [comment]
So I was hoping to write some unit tests before starting with this, but then I realized that the Dumper class is very heavily coupled with rest of the hub, so there is no way to test w/o running the entire hub.

I will implement the changes tomorrow but no unit tests will be added. I will manually test and make sure it works.

**Comment by newgene** [comment]
Sounds good to me. We can test directly in MyVariant hub with dbSNP source.

**Comment by zcqian** [comment]
Changes have been merged
