### ISSUE TITLE
Suspicious behavior of `IndexManager.find_indexer()` method

### ISSUE THREAD

**Issue by erikyao** [biothings/biothings.api#119]
## Code Location

[indexer.py#L908](https://github.com/biothings/biothings.api/blob/master/biothings/hub/dataindex/indexer.py#L908)

## How Indexer Classes are Configured IMHO

Let's start with an example from MyVariant.info. In `config_hub.py` we have:

```python
INDEX_CONFIG = {
        "build_config_key" : "assembly",  # used to select proper idxr/syncer
        "indexer_select": {
            # default
            None : "hub.dataindex.indexer.VariantIndexer",
            # when there's a cold_collection definition
            "build_config.cold_collection" : "hub.dataindex.indexer.ColdHotVariantIndexer",
        },

# Omitted
```

This `indexer_select` dictionary will be passed into `self.indexers` of the `IndexManager` instance ([indexer.py#L871](https://github.com/biothings/biothings.api/blob/master/biothings/hub/dataindex/indexer.py#L871)):

```python
    def configure_from_dict(self, confdict):
        self.es_config = copy.deepcopy(confdict)
        self.indexers.update(confdict.get("indexer_select", {}))

       # Omitted
```

When creating a superhot build in MyVariant.info, usually we will pass an extra json object for additional build configuration, like:

```json
{
    "assembly": "hg38",
    "num_shards": 50,
    "num_replicas": 1,
    "cold_collection": "warm_hg38_20200821_p9z1blfr"
}
```

So the `cold_collection` field name seems to serve as a key to the `hub.dataindex.indexer.ColdHotVariantIndexer` class

## How Indexer Classes are Looked up actually

The suspicious behavior is from the following for-loop inside `IndexManager.find_indexer()` method ([indexer.py#L914](https://github.com/biothings/biothings.api/blob/master/biothings/hub/dataindex/indexer.py#L914) ~ [indexer.py#L936](https://github.com/biothings/biothings.api/blob/master/biothings/hub/dataindex/indexer.py#L936))

```python
        doc = self.src_build.find_one({"_id": target_name})
            if not self.indexers or not doc:
                 return self.__class__.DEFAULT_INDEXER
        
        klass = None
        for path_in_doc in self.indexers:
            if klass is None and (
                    path_in_doc is None
                    or path_in_doc == "default"
                    or path_in_doc == ""):
                # couldn't find a klass yet and we found a default declated, keep it
                strklass = self.indexers[path_in_doc]
                klass = get_class_from_classpath(strklass)
            else:
                try:
                    strklass = self.indexers[path_in_doc]
                    klass = get_class_from_classpath(strklass)
                    self.logger.info(
                        "Found special indexer '%s' required to index '%s'",
                        klass, target_name)
                    # the first to match wins
                    break
                except KeyError:
                    pass
```

Basically, the `klass` returned will be:

- either the default (with `None`, `"default"`, or `""` as key) indexer in `self.indexers` if there is only such indexer configured (pay attention that there is no `break` statement in the above `if` clause)
- or the first non-default indexer found in `self.indexers`

P.S. key order in dictionaries is no longer an issue here because since Python 3.6+, `dict` is insertion-ordered
P.S. the `except KeyError` clause is meaningless in this loop

This look-up scheme ignores the `build_config` at all. What's worse, for builds without `"cold_collection"` configuration, it will still return `ColdHotVariantIndexer` as the indexer, which will fail the assertion in its super class ([indexer.py#L763](https://github.com/biothings/biothings.api/blob/master/biothings/hub/dataindex/indexer.py#L763)):

```python
assert "build_config" in self.hot_build_doc and "cold_collection" in self.hot_build_doc["build_config"], \
            "Can't find cold_collection field in build_config"
```

## Possible Fix?

I think what the original author meant is:

```python
        doc = self.src_build.find_one({"_id": target_name})

        # Omitted

        for path_in_doc in doc["build_config"]:
             # Continue the original code
```

**Comment by namespacestd0** [comment]
Besides the common indexer configuration setup, it seems like the IndexManager also supports setup looking like [{"indexer_type_name": partial},{....}], @newgene @erikyao  can you comment on if this pattern has been used in any of the production hub applications? thank you.

**Comment by namespacestd0** [comment]
`if path_in_doc in doc:` ,as suggested, may not directly achieve what we desire considering `path_in_doc` can be a dotpath with namespace environment access like:
https://github.com/biothings/myvariant.info/blob/cb9c11335efa173ffdb7de6d8c61ef82332f44ef/src/config_hub.py#L77

**Comment by namespacestd0** [comment]
c6d21fae5f150f935cae1e0b4cca50d23e9ae1f1 fixes it, details at https://github.com/biothings/biothings.api/blob/4453537ac9aee1d6665c36ac59550008f22f95ec/biothings/hub/dataindex/indexer.py#L529 @erikyao
