### ISSUE TITLE
Slack Integration to Ping?

### ISSUE THREAD

**Issue by juliamullen** [biothings/biothings.api#128]
I have the BioThings log Slack integration send all debug information to a specific Slack channel. The debug information is useful enough usually (I don't want to turn it off), but drowns out error and exception info when they come in. Is it possible to add a specific user (i.e., me) to get pinged in the Slack integration for messages with logging level >= ERROR?

**Comment by newgene** [comment]
I think this can be split into two improvement tasks:

* Enable slack notifications for `autobuild`, `autopublish` and `autorelease`. Should double check, but I suspect it's not enabled.
* Make "error" notification a bit "stronger", e.g. add `@channel` to the msg.

Will create two separate issues.

**Comment by namespacestd0** [comment]
See sub-issues for details.
