### ISSUE TITLE
tagging @channel for error msgs sent to slack

### ISSUE THREAD

**Issue by newgene** [biothings/biothings.api#130]
With excessive info log msgs, an error or failure msg is very easy to be buried. We can add `@channel` to the msg to make it a bit "stronger". This should also allow users to subscribe for only `@mention` msg.

Currently, we did label error msg with a different color:

https://github.com/biothings/biothings.api/blob/621887f04aae13c3a775aea9aa7daacb92ae7ef0/biothings/utils/slack.py#L9-L12

but probably not good enough.

related to #128

**Comment by namespacestd0** [comment]
Implemented in: https://github.com/biothings/biothings.api/blob/0e5833d8ebdf689bb8529e7d18b7b8870107a722/biothings/utils/loggers.py#L178
