### ISSUE TITLE
remove remaining boto dependency (using boto3 instead)

### ISSUE THREAD

**Issue by newgene** [biothings/biothings.api#133]
We still have a few remaining places using `boto` to access AWS s3 buckets:

https://github.com/biothings/biothings.api/blob/621887f04aae13c3a775aea9aa7daacb92ae7ef0/biothings/utils/aws.py#L6

and

https://github.com/biothings/biothings.api/blob/621887f04aae13c3a775aea9aa7daacb92ae7ef0/biothings/hub/dataexport/ids.py#L4

Most of other AWS related code has been migrated to use boto3. Let's remove the boto dependency completely.

**Comment by zcqian** [comment]
There is one usage not updated in PR #140, in the function `get_s3_file` when `return_what` is set to "content", it returns the contents using `get_contents_as_string` method. In `boto3` there is no equivalent to this. We get `bytes` back and have to decode the `bytes` back to a `str`. However, we do not know the encoding, therefore we have to figure out what encoding to use.

Or, we can read the source code of `boto` and mimic its behavior. This may be somewhat related to Python 2->3 switch where the distinction between the two types is introduced.

**Comment by newgene** [comment]
@zcqian in our case, use default `utf-8` encoding is sufficient. You may leave it as an optional parameter with the default `encoding='utf-8'`.

Don't think we need to backport this method from `boto` to `boto3`. Let's use the way preferred in `boto3`.

**Comment by zcqian** [comment]
@newgene It's not back porting the method, it's figuring out what the behavior is. I read the source code and it actually returns `str` or `bytes` depending on if encoding is specified. And as it turns out, we may be just returning `bytes` as the content all the time.

**Comment by zcqian** [comment]
I just realized another issue with `return_what`. If it's set to `key` it actually returns a `boto.s3.key.Key` object. This is used in:
 - `get_s3_url` which can be easily fixed
 - `publish_data_version` in `hub.py` which takes more effort to fix

However I think the biggest problem with it is that this is a public method in `biothings.utils` and it's hard to know whether other projects/people use this functionality.

**Comment by newgene** [comment]
@zcqian It should be sufficient if you can identify the places using this method or that particular parameter within the "biothings" org and make sure they are updated for the possible back-incompatible change you likely introduce.

**Comment by zcqian** [comment]
@newgene Do we have plans to support AWS GovCloud or the China version of AWS? If not then the `get_s3_url` function can be greatly simplified.

**Comment by newgene** [comment]
no

**Comment by zcqian** [comment]
Closed via #159 see discussions in #140
