### ISSUE TITLE
500 Error when accessing /config in the Hub

### ISSUE THREAD

**Issue by zcqian** [biothings/biothings.api#137]
Commit 473a836 replaced pandas JSON serializer with `orjson`.

However, this caused the unintended side effect where when accessing some endpoints like `/config` we get a 500 error:

```
Uncaught exception GET /config (172.17.0.1)
HTTPServerRequest(protocol='http', host='localhost:7080', method='GET', uri='/config', version='HTTP/1.1', remote_ip='172.17.0.1')
Traceback (most recent call last):
  File "/home/biothings/pyenv/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/usr/lib/python3.8/asyncio/coroutines.py", line 124, in coro
    res = func(*args, **kw)
  File "<string>", line 76, in get
  File "/home/biothings/biothings_studio/biothings/hub/api/handlers/base.py", line 33, in write
    orjson.dumps({
TypeError: Type is not JSON serializable: ConfigurationDefault
```

This results from `orjson` does not serialize arbitrary objects, while pandas does. And in the result generated by `/config`, `ConfigurationDefault` is present as a value somewhere.

Will document discussions and other information in the comments.

**Comment by zcqian** [comment]
A fix is being implemented here: https://github.com/zcqian/biothings.api/blob/ba44899e1599098d70e050c2b96f3fdf2873d594/biothings/hub/api/handlers/base.py#L28-L49

Here another issue occurred: to properly obtain the value of a `ConfigurationValue` type, code has to be executed with other contexts (namely, `name` and `conf`). Such context is not present in the scope which the serializer and handlers are running.

Maybe we should just emit a string? I don't think it's a good idea to emit "code" that is supposed to be `eval`'d or `exec`'d

**Comment by newgene** [comment]
@zcqian agree, just returning a string representation of `ConfigurationValue` is fine to me. We can see if it raises any issue.
