### ISSUE TITLE
Accessing /config in the Hub returns unwanted types

### ISSUE THREAD

**Issue by zcqian** [biothings/biothings.api#138]
This is the root cause for Issue #137 , the dynamically generated handler emits `biothings.ConfigurationDefault` and `biothings.ConfigurationValue` which may not be the wanted types, and cannot be properly handled by the JSON serializer without adding fallback options.

The dynamically generated handler is generated at this location: https://github.com/biothings/biothings.api/blob/8b3630c4ae788d497e579ad9891bdbca8569363a/biothings/hub/api/__init__.py#L19-L144

The actual underlying code for emitting the result is located here: https://github.com/biothings/biothings.api/blob/8b3630c4ae788d497e579ad9891bdbca8569363a/biothings/__init__.py#L131-L147

**Comment by zcqian** [comment]
The consensus is that this is a low priority bug, given that #139 implements a temporary fix. I will document the fields that are `ConfigurationValue` so maybe we can fix those later.

Background:
`ConfigurationValue` is implemented so that code can be used as configuration, it will be `eval`'d or `exec`'d when necessary. I am not certain that it should be handled in the `ConfigurationManager.show` method

**Comment by namespacestd0** [comment]
See #137 for more.
