### ISSUE TITLE
Add a max linenos parameter to hub's log hander

### ISSUE THREAD

**Issue by newgene** [biothings/biothings.api#141]
Currently log file handler reads the whole log file content, let's add a `lines` parameter to allow truncated content returned for the given line numbers (from the latest content):

/log/<logfilename> --> return max of 10,000 lines
/log/<logfilename>?lines=500 --> return last 500 lines

Potentially need a subclass of `tornado.web.StaticFileHandler` here.

**Comment by namespacestd0** [comment]
the affected endpoint should be /logs/ instead of /log/.
