### ISSUE TITLE
`AsyncElasticsearch` issues

### ISSUE THREAD

**Issue by zcqian** [biothings/biothings.api#158]
It seems we are doing imports like this in our code
https://github.com/biothings/biothings.api/blob/0e5833d8ebdf689bb8529e7d18b7b8870107a722/biothings/web/services/health.py#L3

`AsyncElasticsearch` is probably not present in `elasticsearch` Python package under some versions we are using, like 6.3.1, which causes issues on startup and for running tests (as we can see [here](https://github.com/biothings/biothings.api/runs/2923900027?check_suite_focus=true#step:6:33) )

Maybe we should drop the 6.3.1 requirement and move on to the newer version.

**Comment by namespacestd0** [comment]
Yes that's the intention. I'll update the requirements to reflect that.
