### ISSUE TITLE
Expose config settings to limit ES Indexer job concurrency

### ISSUE THREAD

**Issue by newgene** [biothings/biothings.api#164]
Currently, there is a global config setting to control the number of processes in the job queue. ES indexer jobs will use the same job queue. Ideally, indexer job concurrency can be controlled separately, because it uses the prod ES cluster (typically lower capacity comparing to the internal ES cluster for data hub).

We should target to adjust:

* number of concurrent processes
* batch size of each indexer job

**Comment by newgene** [comment]
Might be similar how [MAX_PARALLEL_DUMP](https://github.com/biothings/biothings.api/blob/181a36fc2d5f782bb3608ec032891b0eaa9e7e1d/biothings/hub/dataload/dumper.py#L41) from `BaseDumper` works.

**Comment by namespacestd0** [comment]
Configuration supported through https://github.com/biothings/biothings.api/blob/d7cca7c531165529a437d7ca1cce643535b94727/biothings/hub/dataindex/indexer.py#L472
