### ISSUE TITLE
Doctype error message on ES7

### ISSUE THREAD

**Issue by ravila4** [biothings/biothings.api#165]
The hub error message is:

`DEBUG:hub:Creating new mygeneset_genesetDumper instance
INFO:root:Failed to guess doc_type: Expected only one doc type, got: dict_keys(['dynamic', '_meta', 'properties'])`

Steps for reproducing: Load the 'Releases' tab on mygeneset.info

**Comment by zcqian** [comment]
https://github.com/biothings/biothings.api/blob/d16e12a1708bb8aa45aeda05b8c2fa27a2ef962f/biothings/utils/es.py#L322

try using `elasticsearch` package version 7 and set `include_type_name` to `True` on the call to `get_mapping`. I can't test specifically for at right now (maybe later), but let me know if it solves the problem. If it does resolve the problem, please open a PR.
