### ISSUE TITLE
Upgrade aiocron to 1.6

### ISSUE THREAD

**Issue by namespacestd0** [biothings/biothings.api#180]
See https://github.com/gawel/aiocron/blob/master/CHANGES.rst for more.

**Comment by sengineer0** [comment]
https://github.com/gawel/aiocron/compare/1.3...1.4: @asyncio.coroutine => async def
https://github.com/gawel/aiocron/compare/1.3...1.5: drop 2.7, 3.4 support
https://github.com/gawel/aiocron/compare/1.3...1.5: drop 2.7, 3.4 support
