### ISSUE TITLE
Support post_filter query parameter

### ISSUE THREAD

**Issue by newgene** [biothings/biothings.api#208]
Typically working together with aggregation/facets, `post_filter` allows to filter `hits` list without changing `total` and aggregation output:

https://www.elastic.co/guide/en/elasticsearch/reference/8.1/filter-search-results.html#post-filter

For example:

```
{
  "query": {
    "query_string": {
      "query": "_exists_:@type",
      "default_operator": "AND",
      "lenient": true
    }
  },
  "aggs": {
    "@type": {
      "terms": {
        "field": "@type",
        "size": 100
      }
    }
  },
  "post_filter": {
    "term": {
      "@type": "Dataset"
    }
  },
  "size": 10
}
```

The new `post_filter` can be used to pass a `query_string` query to filter the matching hits:

```
query?q=_exists_:@type&post_filter=@type:Dataset
```

**Comment by newgene** [comment]
We already have an implementation at a particular API instance:

https://github.com/data2health/resource-discovery-api/blob/a7bdc531dde35511ca9ddcb252b58623693adfe3/web/pipeline.py#L73-L77

Now we should move this feature into biothings.web module to make it a generic query feature for all APIs.

**Comment by colleenXu** [comment]
will this work for the POST /query endpoint? As mentioned [above](https://github.com/biothings/biothings.api/issues/208#issuecomment-1068383710), I'm interested in being able to check that a field exists while also querying for certain values in that field and other fields.
