### ISSUE TITLE
Error setting up ES for tests

### ISSUE THREAD

**Issue by ravila4** [biothings/biothings.api#212]
Running local webapp tests on elasticsearch8 fails at this line:

https://github.com/biothings/biothings.api/blob/052d2b3ae84810f345df86e185ea18e730756e99/biothings/tests/web.py#L292-L294

with the errror:

`400 Client Error: Bad Request for url: http://localhost:9200/mychem_test/_doc/_bulk`

According to the [ES documentation](https://www.elastic.co/guide/en/elasticsearch/reference/8.1/docs-index_.html#docs-index_
): 
> From ES8.0, you cannot add new documents to a data stream using the PUT /<target>/_doc/<_id> request format. To specify a document ID, use the PUT /<target>/_create/<_id> format instead.

In this case, the solution is to modify the request url for ES8 to: `http://localhost:9200/{index_name}/_bulk`

**Comment by newgene** [comment]
released in [0.11.0](https://github.com/biothings/biothings.api/releases/tag/v0.11.0)
