### ISSUE TITLE
Can manifest-based data plugins and regular data sources stay in the same folder?

### ISSUE THREAD

**Issue by newgene** [biothings/biothings.api#228]
Right now, manifest-based data plugins stay in a separate folder like "plugins", and regular dumper/uploader based data sources stay in `hub/dataload/sources` folder.

Can we allow them in the same folder? It may just work already, let's verify and try to make it work if not.

- plugins folder example:
   https://github.com/biothings/mydisease.info/tree/master/src/plugins

- regular data sources example:
   https://github.com/newgene/biothings_docker/tree/main/tests/hubapi/demohub/biothing_studio/hub/dataload/sources

**Comment by remoteeng00** [comment]
IMHO, We should not do that:
-  we already have "Export" plugin function (it will export manifest-based plugins, generate plugin's code and put the exported plugin to the same folder with regular plugins
- if we put manifest-based data plugins in the same folder with regular data sources, we will get more complicated to determine which one should be load as manifest-based plugin and which one should be load as regular plugin (it will a bit mess up)

**Comment by ravila4** [comment]
In my experience, we already support having mixed plugin types in the `src/plugins ` folder, but not in the `hub/dataload/sources` folder, which only permits dumper/uploader type plugins. MyGeneset.info is set up with mixed plugin types in the plugins folder.

**Comment by remoteeng00** [comment]
Thanks for help me figure out that we have two types of data plugins: `Manifest-based data plugins` and `“Advanced” data plugins`. And yes they can be placed in the same `src/plugins` folder. 
I offer that we call all "regular dumper/uploader based data sources" that stay in `hub/dataload/sources` folder as "data source" to make it difference to two types of "data plugin", sound good?

**Comment by ravila4** [comment]
Sounds good. @newgene I think we can close this issue, right?

**Comment by newgene** [comment]
Yes, closing this issue now.

@remoteeng00 we typically call both "data plugins": "manifest plugins" and "advanced plugins".
