### ISSUE TITLE
URL for biothings hub config example needs to be fixed in documentation

### ISSUE THREAD

**Issue by kevinxin90** [biothings/biothings.api#23]
In http://docs.biothings.io/en/latest/doc/multiple_sources_tutorial.html

> Before starting to implement our hub, we first need to define a configuration file. A config_common.py <https://github.com/biothings/biothings.species/blob/master/src/config_common.py>

The link provided here is no longer valid. Need to be updated.

**Comment by sirloon** [comment]
@kevinxin90 I think it should point to this one: https://github.com/biothings/biothings.species/blob/master/src/config_hub.py but I want to try following the tutorial again, I'm pretty there are other things either broken or not accurate anymore
