### ISSUE TITLE
Add dumper and uploader timestamps in source metadata

### ISSUE THREAD

**Issue by ravila4** [biothings/biothings.api#230]
I think it would be useful if the API metadata endpoint stored the timestamps when the uploader/dumper last ran for a datasource. This could allow the user to know when a specific data source was last updated (which often differs from the date in the version field).

The metadata for a datasource can be found in the `/metadata` endpoint. Currently it looks like this (using Wikipathways in https://mygeneset.info/metadata as an example):

```
{
  "biothing_type": [
    "geneset"
  ],
  "build_date": "2021-10-20T16:26:40.305000-07:00",
  "build_version": "__multiple__",
  "src": {
    "wikipathways": {
      "licence": "CC0 1.0 Universal",
      "code": {
        "file": "src/plugins/wikipathways/upload.py",
        "repo": "https://github.com/biothings/mygeneset.info.git",
        "commit": "e737e80",
        "branch": "master",
        "url": "https://github.com/biothings/mygeneset.info/tree/e737e80b8f464dce2599acffe1de60f727235094/src/plugins/wikipathways/upload.py"
      },
      "stats": {
        "wikipathways": 1770
      },
      "version": "20210710",
      "license_url": "https://www.wikipathways.org/index.php/WikiPathways:License_Terms",
      "url": "https://www.wikipathways.org/"
    },
...
```

I suggest we can add two fields named `upload_date` and `dump_date` for each datasource, under the `src` field.
I think this might involve adding these fields in mongodb under `src_build._meta`, and populating with the timestamps from `src_dump.download` and `src_dump.upload` whenever a build is created.

**Comment by vincerubinetti** [comment]
Maybe `download_date` isntead of `dump_date` for consistency with `src_dump.download`?
