### ISSUE TITLE
display optional "description" in API metadata

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings.api#236]
If a user wants to know what a given API is for (e.g., "repodb"), the best options now seem to be to search the API name and/or look at example records.  We should also allow an optional "description" to be provided in the manifest.json metadata, which would optionally provide some human-readable description directly on the API page.

**EDIT**: Sorry, just realized I should probably have created this issue in https://github.com/biothings/pending.api/issues..  Feel free to recreate it over there if helpful.

**Comment by newgene** [comment]
`__metadata__` should already allow to add optional fields like "description" or anything else. It should then be carried over to the /metadata endpoint:

https://github.com/erikyao/repoDB/blob/9ce8f57e84b08c880ebdfd2a513829aa7c1db353/manifest.json#L4-L8

Let's give it a try for the `repodb` data plugin, the pending API UI will need to be updated to display this "description" text when available.

**Comment by erikyao** [comment]
After the bugfix ([pending.api - Issue#77](https://github.com/biothings/pending.api/issues/77)) and description augmentation ([repoDB - PR#2](https://github.com/erikyao/repoDB/pull/2)) , [repoDB API](https://biothings.ncats.io/repodb) is updated. However the description is not shown.

I can see that the API page requests metadata from https://biothings.ncats.io/repodb/metadata, and the description is inside the response. Therefore I think it now boils down to a frontend problem. 

To @newgene: shall we have @marcodarko involved?

**Comment by newgene** [comment]
Yes, web UI needs to be updated accordingly as well (@marcodarko)

**Comment by marcodarko** [comment]
Working on this project right now, I'll add it to my PR

**Comment by marcodarko** [comment]
Will be addressed in https://github.com/biothings/pending.api/pull/78

**Comment by tokebe** [comment]
Following up: has this issue been adequately addressed by the above merged PR / should this issue be closed?

**Comment by marcodarko** [comment]
Descriptions are now available eg. [repodb](https://biothings.ncats.io/repodb)
