### ISSUE TITLE
Make `tests/hub/datarelease/test_releasenote.py` runnable within our current testing Github Action

### ISSUE THREAD

**Issue by erikyao** [biothings/biothings.api#241]
Tests involved: https://github.com/biothings/biothings.api/blob/0.11.x/tests/hub/datarelease/test_releasenote.py. It has its own `conftest.py` that creates and deletes the `HUB_CONFIG`-related files, and it's individually runnable from its local folder. (maybe I should check my PyCharm settings on Pytest)

Error message: https://github.com/newgene/biothings.api/runs/7158195473?check_suite_focus=true

Our current Github Action that runs all the tests: https://github.com/newgene/biothings.api/blob/master/.github/workflows/run-tests.yml

Advice from Chunlei:

> note that `HUB_CONFIG: 'tests.test_config'` line, maybe you need to add something to this file?

> your tests need to be runnable at the root via `pytest tests`

Side Quest: to setup a standard procedure for tests involving individual config?

**Comment by newgene** [comment]
should be resolved in this merged PR: https://github.com/newgene/biothings.api/pull/42. Also this PR: https://github.com/newgene/biothings.api/pull/43 resolves a test failure in Python 3.6.

@erikyao please verify it works as expected.

**Comment by erikyao** [comment]
Fixed with commit 4bd607b58bbe3dade3fbaa135f7fd587b84d61fa
