### ISSUE TITLE
indexer should check _id length, skip if too long and raise a warning

### ISSUE THREAD

**Issue by newgene** [biothings/biothings.api#253]
Elasticsearch has a [512 length limit](https://www.elastic.co/guide/en/elasticsearch/reference/8.4/mapping-id-field.html) for the `_id` field. Indexer class should check `_id` length, skip docs if too long, and raise a warning in the logs, instead of raise an exception.

See an example at https://github.com/biothings/biothings.api/issues/252

**Comment by colleenXu** [comment]
Do we need to note a length limit in documentation like this? https://docs.biothings.io/en/latest/tutorial/studio.html#parser

**Comment by newgene** [comment]
@colleenXu good catch! Added the length limit to our document.
