### ISSUE TITLE
Fix Aggregation Web formatter 

### ISSUE THREAD

**Issue by jal347** [biothings/biothings.api#267]
Histogram aggregations do not contain the fields `aggregations.<term>.doc_count_error_upper_bound, aggregations.<term>.sum_other_doc_count`

In our es formatter, it assumes that these two values exist. https://github.com/biothings/biothings.api/blob/master/biothings/web/query/formatter.py#L426-L427

When making a custom aggregation in the esquerybuilder, I have to override these two values. 
```
res[facet]['other'] = res[facet].pop('sum_other_doc_count', 0)
res[facet]['missing'] = res[facet].pop('doc_count_error_upper_bound', 0)
```
We should have this as a quick fix so when other users make custom aggregations they wont have to override the transform_aggs method.

**Comment by newgene** [comment]
released in [0.12.0](https://github.com/biothings/biothings.api/releases/tag/v0.12.0)
