### ISSUE TITLE
dumper URL attachment filename not respected

### ISSUE THREAD

**Issue by greg-k-taylor** [biothings/biothings.api#3]
Priority:  Low

Consider the following URL which downloads a file named "HomoSapiens_binary_hq.txt".
http://hint.yulab.org/download/HomoSapiens/binary/hq/
For the dumper to download this file, the URL provided must remove the trailing slash, which then results in the filename of 'hq' being downloaded.

Desired Behavior:
The original URL to be provided and for the attachment filename to be observed when downloading the file.

Workaround:
Remove the trailing slash in the URL and use the 'hq' directory name as the filename.

Curl Output:
$ curl -I http://hint.yulab.org/download/HomoSapiens/binary/hq/
HTTP/1.1 200 OK
Date: Thu, 12 Apr 2018 16:14:12 GMT
Server: Apache
X-Frame-Options: SAMEORIGIN, SAMEORIGIN
Content-Disposition: attachment;filename="HomoSapiens_binary_hq.txt"
Content-Type: application/octet-stream

**Comment by sirloon** [comment]
@greg-k-taylor fyi fixed in 530ad9e83787c373526562bdc5900308b46945af

**Comment by sirloon** [comment]
Fix has a side-effect, it doesn't respect local filename setting when explicitly passed

**Comment by sirloon** [comment]
new fix in c7e4e2d49ca40f9df72ccfd1ac238774f3274154 (also in 0.2.2 branch
