### ISSUE TITLE
convert "msgpack=1" option to "format=msgpack"

### ISSUE THREAD

**Issue by newgene** [biothings/biothings.api#31]
Historically, we support msgpack output format with "msgpack=1" option. We should consolidate this option into "format" query parameter:

"format=json|msgpack|yaml"

**Comment by namespacestd0** [comment]
Implemented in https://github.com/biothings/biothings.api/commit/bfb60c2ea9fd01b32e9eed1d78f8eeee8c3cb4d6 by @cyrus0824

**Comment by namespacestd0** [comment]
Deployed on 6/21. Tests passed on mygene.info.
