### ISSUE TITLE
uploader.switch_collection error in `biothings-cli dataplugin upload`

### ISSUE THREAD

**Issue by newgene** [biothings/biothings.api#357]
To reproduce this:

```
git clone git@github.com:biothings/DGIdb.git
cd DGIdb
biothings-cli dataplugin dump  # this work fine
biothings-cli dataplugin upload # raise the error below
```

```
Traceback (most recent call last):
  File "/Users/cwu/opt/testpy/lib/python3.12/site-packages/biothings/hub/dataload/uploader.py", line 273, in switch_collection
    raise ResourceError("No temp collection (or it's empty)")
biothings.hub.dataload.uploader.ResourceError: No temp collection (or it's empty)
```

Run this with `BTCLI_DEBUG=1` should turn on full traceback:

```
BTCLI_DEBUG=1 biothings-cli dataplugin upload
```

The same error from other data plugin, both the latest `1.0.x` branch and the recent `0.12.5` release.
Not sure if it's relevant, I am running it under Python 3.12.

**Comment by ctrl-schaff** [comment]
@newgene I think the datasource may be broken. Going to the [webpage](https://www.dgidb.org/data/monthly_tsvs/2022-Feb/interactions.tsv) yields a 404 and this is reflected in the data pulled down. If you look at `interactions.tsv` pulled down by the uploader it's the following:

```html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <link rel="icon" href="/favicon.png" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <meta name="theme-color" content="#000000" />
    <meta name="description" content="DGIdb, The Drug Gene Interaction Database, is a research resource that can be used to search candidate genes or drugs against the known and potentially druggable genome." />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Fira+Sans:wght@300;350;400;500;700;800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@100;300;350;400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Work+Sans:wght@200;300;350;400;500;600&display=swap" rel="stylesheet">
    <link rel="apple-touch-icon" href="/dgidb-icon_48.png" />
    <link rel="manifest" href="/manifest.json" />
    <title>DGIdb</title>
    <script defer="defer" src="/static/js/main.dfda9c33.js"></script>
    <link href="/static/css/main.00bb919d.css" rel="stylesheet">
</head>

<body><noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="root"></div>
</body>

</html>
```
Which looking at the error produced by the biothings-cli this makes sense. It uploads zero documents and is unable to find a temp table for uploading because there's no data


If you look at the download section it appears the internal url path they use for hosting the tsv files has changed. In our manifest we have it as the following:

```json
{
    ...
    "data_url": ["https://www.dgidb.org/data/monthly_tsvs/2022-Feb/interactions.tsv"],
    ...
}
```

If you remove the `monthly_tsvs` path it appears to work again
```json
{
    ...
    "data_url": ["https://www.dgidb.org/data/2022-Feb/interactions.tsv"],
    ...
}
```

**Comment by ctrl-schaff** [comment]
They appear to have something that points to the latest data so we wouldn't have to update it. https://www.dgidb.org/data/latest/interactions.tsv

**Comment by newgene** [comment]
@ctrl-schaff thanks for your quick check! It makes sense now, although the error seems quite profound to the end user. We probably can add a warning when the parser has zero output, and catch the error earlier. This issue is now much less urgent than I previously thought.

**Comment by newgene** [comment]
A new issue #358 created to replace this one. Upon completion, we should have a more explicit error message in this case. 

Close this one now.
