### ISSUE TITLE
return_json method needs to be renamed

### ISSUE THREAD

**Issue by newgene** [biothings/biothings.api#36]
Since we now have a "format" parameter to support json/yaml/msgpack/html output format, we should have a generic "return_data" method to replace those used where "return_json" currently is used.

we should have:

```
return_json  (a new one)
return_yaml
returm_msgpack
return_html
```

and then a generic ```return_data(self, format='json|yaml|msgpack|html',...)``` method.

After the above change, make sure we double_check in biothings/mygene.info, biothings/myvariant.info, biothings/mychem.info, etc where "return_json" might be used.

related to #31 #32.

**Comment by namespacestd0** [comment]
Fulfilled in bfb60c2ea9fd01b32e9eed1d78f8eeee8c3cb4d6 by @cyrus0824 

I created a new common test class to cover this output format functionality, extensible for other future common query endpoint tests in https://github.com/biothings/biothings.api/commit/48984b9ab60c14c5d47ee329ef906d47b35b8ade.

**Comment by namespacestd0** [comment]
Deployed on 6/21. Tests passed on mygene.info.
