### ISSUE TITLE
remove all httplib2 dependency

### ISSUE THREAD

**Issue by newgene** [biothings/biothings.api#37]
In all our all biothings main applications, ```httplib2``` package was replaced by ```requests``` now. The only places still use ```httplib2``` is all the test code, including:

biothings/biothings.api/biothings/tests
biothings/biothings.api/biothings/conf/biothings_templates/es_project_template/tests

and all the API application tests:

biothings/mygene.info/src/tests
biothings/myvariant.info/src/tests
biothings/mychem.info/src/tests

(Searching for httplib2 in biothings github org might discover more place like above)

Let's remove the use of ```httplib2```.

**Comment by namespacestd0** [comment]
See #39 for implementation in biothings.api
mygene tests are updated accordingly: https://github.com/biothings/mygene.info/pull/59/commits/324501ecb0c26fbea838203fc54cf1608cdc1c38
the same changes are proposed to make in myvariant.info and mychem.info
