### ISSUE TITLE
An easy way to return random docs

### ISSUE THREAD

**Issue by newgene** [biothings/biothings.api#38]
When inspecting API data, it could be very handy to return some random docs. By default, it returns one doc, but allow to pass a `size` parameter to return a list of docs (up to 1000).

A pretty decent ES query here: https://stackoverflow.com/questions/25887850/random-document-in-elasticsearch

It can be implemented as this:

```
/query?q=__any__   (similar to /query?q=__all__)
```

**Comment by namespacestd0** [comment]
Implemented. Please review: https://github.com/namespacestd0/biothings.api/commit/c614cfd1c4691cf4d50634d22e060b81831650c4
Will merge the changes then.

**Comment by newgene** [comment]
@namespacestd0 let's add some corresponding tests, other than that, all look good to me.

**Comment by sirloon** [comment]
@namespacestd0 @newgene considering my tests on pending API "fire", 8.6 billion docs, I think this option should be optional, maybe even defaulting to "not activated", as it can really put a lot of stress on the cluster (with "fire", it runs almost 60s, cluster cpu/load red). I'm wondering about myvariant, pretty sure it would add a significant overhead, possibly opening DDoS attacks. 

(or the implementation should be different)

**Comment by namespacestd0** [comment]
Added smartapi test case https://github.com/SmartAPI/smartAPI/blob/d29086439282a520215cbbd81d95ead9fa364ade/src/tests/remote.py#L37 in response to https://github.com/biothings/biothings.api/issues/38#issuecomment-459527423
@cyrus0824 implemented functionality switch https://github.com/biothings/biothings.api/commit/6c02376b4efb988ebf3cf9b29f59b997aa2b3170 that turns this feature off by default in response to https://github.com/biothings/biothings.api/issues/38#issuecomment-468061144
I am looking for a more efficient method that can be used universally in the future regardless of database size.

**Comment by namespacestd0** [comment]
A quick pseudo-random solution would be going to a random page of match_all query. The internal switch can instead control if we are returning the result of this implementation of the other one.
