### ISSUE TITLE
always_list not working when having dotfield=true

### ISSUE THREAD

**Issue by kevinxin90** [biothings/biothings.api#43]
Example: http://mychem.info/v1/query?q=siltuximab&fields=drugbank&dotfield=true&always_list=drugbank.enzymes.actions

**Comment by namespacestd0** [comment]
I think this issue was fixed early this year.
![image](https://user-images.githubusercontent.com/25359322/102284206-a1092d00-3ee8-11eb-8e19-047684bd9c2d.png)
