### ISSUE TITLE
POST query support multiple value combinations from multiple fields

### ISSUE THREAD

**Issue by newgene** [biothings/biothings.api#49]
here is a use case from MyVariant.info: https://github.com/biothings/myvariant.info/issues/89.

Possible solution:

q="1|12345,2|1000", scopes="chrom|vcf.position"

Using "|" to separate the value combination in `q` and the corresponding field combination in `scopes`.

A few other notes:
* "|" may not be the best choice, need to pick one won't be used in the value itself and the query separator.
* The number of value/field combination must match.
* Should set a cap for maximium number of value/field combinations (10 should be good enough)
* should be 100% back compatible with the current behavior
* can still have multiple fields to match one value, i.e., this should work: `q=val1|val2&scopes=fld1,fld2|fld3`, where val1 should match either fld1 or fld2.

**Comment by namespacestd0** [comment]
Syntax shown in an example here:
```
{
  "q": [["CDK2", "c.314A>T"], ["CXCR4", "c.535G>C"]],
  "scopes": [["dbsnp.gene.symbol", "snpeff.ann.genename"], "snpeff.ann.hgvs_c"]
}
```
will basically be equivalent to 
```
[
    {
        "query": {
            "bool": {
                "must": [
                    {
                        "multi_match": {
                            "query": "CDK2",
                            "operator": "and",
                            "fields": [
                                "dbsnp.gene.symbol",
                                "snpeff.ann.genename"
                            ]
                        }
                    },
                    {
                        "multi_match": {
                            "query": "c.314A>T",
                            "operator": "and",
                            "fields": "snpeff.ann.hgvs_c"
                        }
                    }
                ]
            }
        }
    },
    {
        "query": {
            "bool": {
                "must": [
                    {
                        "multi_match": {
                            "query": "CXCR4",
                            "operator": "and",
                            "fields": [
                                "dbsnp.gene.symbol",
                                "snpeff.ann.genename"
                            ]
                        }
                    },
                    {
                        "multi_match": {
                            "query": "c.535G>C",
                            "operator": "and",
                            "fields": "snpeff.ann.hgvs_c"
                        }
                    }
                ]
            }
        }
    }
]
```
Implemented in 89c0e0ce21658b9e8a1d49a945bd3701e4a9d6bb
Tests/examples in 996420a82106b0ca03bac74f36af4c6431248ced
Myvariant use cases/tests in https://github.com/biothings/myvariant.info/commit/fc7fac7da23f5781000be7da3645a36402b6d2c5
Pending deployment.

**Comment by kevinxin90** [comment]
@namespacestd0 Is this feature deployed? Tried  on myvariant, seems not working at the moment.

**Comment by namespacestd0** [comment]
This feature should be universally available on all major biothings instances now.

**Comment by newgene** [comment]
for reference, these two tests provide some example queries:

https://github.com/biothings/biothings.api/blob/6dce4ce2e07a6c42be1a02d9049b25767c97b8f3/tests/web/handlers/test_query.py#L780-L828
