### ISSUE TITLE
enable a readyonly/public view of the studio web app

### ISSUE THREAD

**Issue by newgene** [biothings/biothings.api#57]
Alternative is to create separate public pages/tabs instead of disabling dev-only features on the current pages/tabs.

**Comment by sirloon** [comment]
Is it 1) "just" about the UI, ie. removing actions/button which could change data in any way, or 2) is it also about having the Hub (through API) being read-only ? If 2) it means we need to authenticate users. If 1) I can come with a solution where we could switch to "read-only" in UI while the hub would remain as it is.

**Comment by sirloon** [comment]
done in studio 0.2b / biothings 0.7.x
