### ISSUE TITLE
Working with local (only) files

### ISSUE THREAD

**Issue by BioComSoftware** [biothings/biothings.api#68]
Hello, 

I'm not having any luck finding this in the documentation. I've gone through the tutorial [here](https://biothingsapi.readthedocs.io/en/latest/doc/studio.html#part-2-multiple-datasources) using the Docker container for Biothings Studio. It worked fine, however the data files are, of course, downloaded form a Github. 

Do you have any documentation on how to use Biothings (either Studio, or any other flavor like standalone) to accomplish the same end result as the tutorial - but **using local data files only** (I.e. TSV files that live locally on the same machine/docker container as Biothings Studio itself.)

Placing the data files in a github or S§ is not an option. 

My ultimate goal is to create an entirely automated Biothings pipeline, which ends in a running API, from files that will be copied to a local directory. 

Thanks!

**Comment by sirloon** [comment]
Hi, just to clarify, in the tutorial, code is fetched from github, but then the data downloaded by the dumper (that dumper is generated according to what's in manifest.json) is from a http server (see data_url section in manifest). You can also use FTP protocol.

So, the answer is yes, you can use local files only. 2 options:
1. you run a FTP server somewhere in your network, or your docker host, and put ftp://server/file URLs in manifest.json
2. you send (feed) the studio with some data that will be stored within the container. Not documented yet, but  here's the procedure. Assuming you want to upload a file named "myfile.csv" into the studio, file currently located on your host in /tmp/myfile.csv, and assuming that file is part of a data source named "mysrc". 

```
# upload a file to the studio, "mysrc" is the datasource name
# the file is for, /tmp/myfile.csv is path to the file to upload
curl  -F 'data=@/tmp/myfile.csv' http://localhost:7080/dataupload/mysrc
# then you can add the local URL in the manifest (port 8080, not 7080)
http://localhost:8080/dataupload/mysrc/blabla
```

Studio will generate a dumper for you, and download this from its own HTTP server. So the csv will be duplicated from where it's been upload with curl, to when it's been downloaded by the dumper. If this is not something you want (convenient but not ideal), I suggest you store that csv file directly on the docker, server by http or ftp, and use that server in data_url instead.

Hope it makes senses. I closing the ticket but feel free to re-open if you have more questions.

**Comment by newgene** [comment]
And I want to add another note that, as another alternative, you can easily to start a http server to serve a local folder with this one-liner in Python:
    
    python3 -m http.server

Run it from the local folder contain your data file.

more here: https://blog.anvileight.com/posts/simple-python-http-server/
