### ISSUE TITLE
figure out how to adjust batch_size for ES deployment

### ISSUE THREAD

**Issue by newgene** [biothings/biothings.api#70]
For smaller hub, the default batch size tends to crash the ES server.

**Comment by namespacestd0** [comment]
The batch_size has side effect on concurrency. It is explained in 6/22 meeting. The current control setting should be used alongside with max hub worker for said purpose. See https://github.com/biothings/biothings.api/blob/af4f6ea030442c9f4fa09d8dcd9cf5fd1578c767/biothings/utils/es.py#L234 and https://github.com/biothings/biothings.api/blob/af4f6ea030442c9f4fa09d8dcd9cf5fd1578c767/biothings/hub/dataindex/indexer.py#L319 for details.
