### ISSUE TITLE
Improve Google Analytics Mixin

### ISSUE THREAD

**Issue by namespacestd0** [biothings/biothings.api#72]
The tracking component could be improved to make more efficient API calls and gather additional facets of request data. The customization for different APIs can be made easier to access.

**Comment by zcqian** [comment]
So we want to improve `GAMixIn` in `biothings/utils/web/analytics.py` ? What's the detailed plan?

**Comment by newgene** [comment]
While improving GAMixin, please note this new GA4 migration:

https://blog.google/products/marketingplatform/analytics/new_google_analytics

also the changes posted here:

https://developers.google.com/analytics/devguides/config/mgmt/v3/batching

**Comment by namespacestd0** [comment]
resolved in be3aa637035c91ec60c57869cafc99bf80342664
