### ISSUE TITLE
Increase build page loading speed

### ISSUE THREAD

**Issue by namespacestd0** [biothings/biothings.api#74]

**Comment by namespacestd0** [comment]
The reason for the slow load seems to be related to the front end. Karthik identified the backend api response speed is fair.

**Comment by namespacestd0** [comment]
@marcodarko can you point to the fix commit? we should be able to close this issue.

**Comment by marcodarko** [comment]
@namespacestd0 https://github.com/biothings/biothings.api/commit/39d911eccce38d1ea1ee094c51ba443c247ee7bf I think this was the one I worked on
