### ISSUE TITLE
"Show all" button can't be cliked in 'Sources' tab because pop-up dialog dissapears on hover

### ISSUE THREAD

**Issue by ravila4** [biothings/biothings.api#83]
This affects the the master branch version. When loading https://studio.biothings.io/master/#/, the behavior appears normal in the Home, Builds, Releases, and API tabs, but after navigating to the 'Sources' tab, the pop-up dialog starts misbehaving. If you click on any of the other tabs after that, the pop-up remains broken until you refresh the page.

![Peek 2020-08-19 18-16](https://user-images.githubusercontent.com/9020496/90705767-8bd90600-e248-11ea-909b-e30aede5dbf1.gif)

**Comment by newgene** [comment]
Fixed in this pull request: https://github.com/biothings/biothings.api/pull/88
