### ISSUE TITLE
allow multiple hits returned from annotation endpoint 

### ISSUE THREAD

**Issue by newgene** [biothings/biothings.api#84]
Unfortunately, there are still some edge cases for some biological ids which can have multiple matching objects. For example, dbsnp rsid can match multiple variant objects:

http://myvariant.info/v1/variant/rs2267

Currently, it returns

```
{
"code": 404,
"success": false,
"error": "not a unique id."
}
```

Unless the upstream data source resolves this multiple matches, we should just return all matching objects in an array. In previous version, the output in such cases will be an array, but we can discuss if any better way to return the results.

**Comment by namespacestd0** [comment]
Implemented in 97f949c4a743a1710a638809d4e1a28e042907e8
