### ISSUE TITLE
Error message when running docker container (0.2b) 

### ISSUE THREAD

**Issue by dongbohu** [biothings/biothings.api#90]
When running this command to start the docker container version `0.2b`:
```
docker run --rm --name studio -p ... biothings/biothings-studio:0.2b
```
I saw the following error messages on the terminal:
```
ERROR: elasticsearch-dsl 7.1.0 has requirement elasticsearch<8.0.0,>=7.0.0, 
but you'll have elasticsearch 6.3.1 which is incompatible.
```
which must be generated by `pip` when it installs elasticsearch dependency packages.

Since ElasticSearch indexing actually worked in the container, this is probably more like a warning than an error. But it should be easy to fix to avoid any potential incompatibility.

**Comment by zcqian** [comment]
Latest Dockerfiles produce working images. Closing issue. See https://github.com/biothings/biothings_docker
