### ISSUE TITLE
Store and display full traceback for dumper/uploader exceptions

### ISSUE THREAD

**Issue by newgene** [biothings/biothings.api#92]
Currently we only store the last error msg from an exception:
![image](https://user-images.githubusercontent.com/130158/97633323-285e1800-19f1-11eb-827e-6846396dbde6.png)

Ideally, we should store and optionally display the full traceback.

**Comment by newgene** [comment]
We can also include the log file (those task-specific log files) info as well, either display the latest logs or minimally display the full path of the log file, so that developers can check it from the command line.

**Comment by namespacestd0** [comment]
Implemented in https://github.com/biothings/biothings.api/commit/ff9da01b365ebddbc817699e80ff54fa346c73da
