### ISSUE TITLE
running tests based on BiothingsTestCase class without config.py

### ISSUE THREAD

**Issue by newgene** [biothings/biothings.api#95]
To test remote API server, we currently can do it like this:

    TEST_HOST=http://mychem.info  PYTHONPATH=. pytest -v test_mychem.py

this requires creating an empty `config.py` file in the current folder. We can remove this requirement.

**Comment by namespacestd0** [comment]
Implemented in biothings.tests.web, mychem test cases updated, need to update others.

**Comment by namespacestd0** [comment]
https://github.com/biothings/biothings.api/blob/81d20692e9dabc734bad0c026b660bf75c40d944/biothings/tests/web.py#L27-L31
will test a server without config files.
